server:
 port: 9009
spring:
 datasource:
   url: jdbc:mysql://localhost:3306/your_database
   username: jon
   password: ''
   driver-class-name: com.mysql.cj.jdbc.Driver
   hikari:
     maximum-pool-size: 10
     minimum-idle: 5
     idle-timeout: 30000
     connection-timeout: 30000
     max-lifetime: 1800000

 jpa:
   hibernate:
     ddl-auto: update
     show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
       format_sql: true
       use_sql_comments: true
       jdbc:
         lob:
           non_contextual_creation: true


